### ISSUE TITLE
Atom selection not synchronized when clicking on the 3D representation

### ISSUE THREAD

**Issue by avirshup** [Autodesk/notebook-molecular-visualization#32] opened 2016-10-29 00:59 UTC
The selection state isn't always synced up between the 2d, 3d and text displays.

Here's a gif illustrating some of this: (generated with `mol = mdt.from_name('caffeine'); mol.draw()`)
![selectionlist](https://cloud.githubusercontent.com/assets/9388007/19826091/def242c0-9d37-11e6-94ec-15f1aa90bab3.gif)

There are 3 specific symptoms here:
- After deselecting all atoms, the text display continues to show the last selected atom
- The 2D selections usually aren't getting updated along with the 3D 
- Every time I select an atom in 3D, the 2D representation jumps a little a bit

**Comment by justinmc** [comment] 2016-10-31 17:23
Some notes:

For point 1, that was due to a bug in ipywidgets (https://github.com/ipython/ipywidgets/issues/738) that I should have fixed.  I need to make sure that the fix got released and that it does fix this problem.

Point 2 I'll have to look into using this molecule.  I have occasionally seen specific atoms that just don't ever show up as selected in 2D, maybe this has to do with that.

Point 3 has been haunting me for awhile...  I think this is another reason to move off of D3.

**Comment by justinmc** [comment] 2016-11-01 23:45
@avirshup Regarding point 1, I just confirmed that it is fixed when using ipywidgets v6.0.0b1.  What's the process for upgrading us, just changing requirements.txt both here and in mdt?  Or do we not want to upgrade until it's out of beta?

**Comment by avirshup** [comment] 2016-11-01 23:54
Yeah, requirements.txt is is the only thing to change for now. I'll be merging in some preliminary conda environment.yml files, which will complicate matters, but we can worry about those later.

I'm certainly fine with the dev version having dependencies on a beta `ipywidgets`, although I'm less comfortable with having a beta dependency in the next stable release.

(BTW, when this nbmolviz next gets released, I think it's worth AT LEAST a bump to 0.7, given how much it's been improved :) )

**Comment by justinmc** [comment] 2016-11-02 00:24
Alright that sounds reasonable.  I've been putting it off, but I think it looks pretty broken when the last atom doesn't deselect.  I'll go ahead and do PRs for upgrading those and hope that the ipywidgets people get it stable before we next want to release.

**Comment by justinmc** [comment] 2016-11-02 00:24
Point 2 fix is here: https://github.com/Autodesk/molecule-2d-for-react/pull/17

**Comment by justinmc** [comment] 2016-11-02 17:31
Point 1 fixed in two PRs:
https://github.com/Autodesk/notebook-molecular-visualization/pull/37
https://github.com/Autodesk/molecular-design-toolkit/pull/114

**Comment by justinmc** [comment] 2016-11-02 22:21
@avirshup The fixes for 1 and 2 are merged.  Do you mind if I close this issue and create a new one for fixing the "jumpiness", probably by moving off of D3?

**Comment by avirshup** [comment] 2016-11-02 22:50
@justinmc - sounds good; just tested everything and it's working well!

And yeah, the D3 issue is not nearly as important as the other two, so feel free to close this one.

**Closed as completed** 2016-11-03 00:16 UTC
Labels: bug

**Comment by justinmc** [comment] 2016-11-03 00:19
This issue will track the D3 jump: https://github.com/Autodesk/molecule-2d-for-react/issues/9
